### ISSUE TITLE
No datasource for type 'postgis' found (during parsing of layer in mapnik.xml file)

### ISSUE THREAD

**Issue by hb0** [mapsquare/docker-mapnik3#2]
Hi. First of all: Great Docker image, very clean :+1: 

I want to use it in an own Dockerfile and include it with:
`FROM jawg/mapnik3:3.0.15`

Then I install further dependencies: mod_tile, apache2, supervisor
As I need to execute further steps in my own entrypoint script I reference this script in ENTRYPOINT[].
When I now start the container (it worked before with the mapnik-dev 2.3 nightly ppa) renderd complains, that the postgis plugin is not installed.

I am wondering, if it's a problem that I don't execute:
ENTRYPOINT ["mapnik-render"]
But I was not able track down what this command is executing.

**Comment by Joxit** [comment]
Hi, Thx for using our docker image and give us feedback :smile: 

Do you have these lines in your renderd configuration?

```
[mapnik]
plugins_dir=/usr/local/lib/mapnik/input/
```
`plugins_dir` is important to locate the postgis plugin and should not work with the default renderd value.

`mapnik-render` is just the default mapnik utily

**Comment by hb0** [comment]
Hi @Joxit !
Thank you so much for this hint, so simple but so effectiv :+1: 
_(My default previous location was: /usr/lib/mapnik/input)_
The errors are gone and everything is rendering as it used to :-)

Just that I understand your last line correctly: It's just a dummy re be replaced with e.g.:
> /bin/bash -c "renderd -f -c /usr/local/etc/renderd.conf 2>&1 | tee -a /var/log/renderd"

_Keep up the good work!
I'll redo the installation code in my Dockerfiles according to your Dockerfile, it's so clean compared to mine ;-)_

**Comment by Joxit** [comment]
You are welcome :smiley: 
I might add a symbolic link between the two folders to be compatible with the default renderd configuration. :-)

`mapnik-render` is a binary built with mapnik that can be used to check if mapnik is working properly (with its plugins).

Thx, have a nice day :wink:

**Comment by frodrigo** [comment]
The symblink is here but, I still have the same issue

```
mapnik-render /p/mapnik.xml out.png
Error Could not create datasource for type: 'shape' (no datasource plugin directories have been successfully registered)  encountered during parsing of layer 'images' in Layer of '/p/mapnik.xml'
```

**Comment by Joxit** [comment]
Hi @frodrigo Sorry for the delay :slightly_smiling_face: 

This is related to [mapnik#4010](https://github.com/mapnik/mapnik/issues/4010) and [mapnik#3373](https://github.com/mapnik/mapnik/issues/3373).
> mapnik-render at this point is only designed to be used locally, from within a mapnik git clone. So it is not expected to work if installed.

If you need this to work, the workaround is
```sh
mkdir -p plugins && ln -s $(mapnik-config --input-plugins) plugins/input
mapnik-render /p/mapnik.xml out.png
```

I know, this is not elegant :man_shrugging:
