### ISSUE TITLE
How to use it with Python bindings?

### ISSUE THREAD

**Issue by qxang** [mapsquare/docker-mapnik3#3]
Hi, it is great docker image, but can you provide one example for it with python bindings? Thank you.

**Comment by Joxit** [comment]
Hi,
This image does not include mapnik python binding. 
But you can use `jawg/mapnik3` as a base image for a python binding.

There are some informations in [mapnik/python-mapnik branch v3.0.x](https://github.com/mapnik/python-mapnik/tree/v3.0.x) repository for the installation.

**Comment by qxang** [comment]
I see. Thank you very much.

**Comment by Sieboldianus** [comment]
Had to do this. Here's how to follow @Joxit suggestion:

```Dockerfile
FROM jawg/mapnik3:3.1

ENV PYTHON_BINDINGS=" \
    autoconf \
    apache2-dev \
    libtool \
    libxml2-dev \ 
    libbz2-dev \
    libgeos-dev \ 
    libgeos++-dev \
    gdal-bin \
    python3 \
    python3-pip \
    python3-mapnik \ 
    python3-psycopg2 \
    python3-yaml"

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        $PYTHON_BINDINGS
```

Build the image:
```bash
docker build --tag mycontainers/mapnik3_python .
```

Then startup/run mapnik, e.g:
```bash
docker run --rm \
    --volume $(pwd)/data-test:/data-test \
    --volume ~/.fonts:/fonts \
    --volume $(pwd)/mapnik-docker-test:/mapnik-test \
    --volume $(pwd)/output:/output \
    docker.io/mycontainers/mapnik3_python \
    /bin/bash -c "python3 /mapnik-test/tagmap_xml.py"
```

I have added the [Dockerfile here](https://github.com/Sieboldianus/docker-mapnik3-python).
